/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: detect_pipe.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "detect_pipe.pb-c.h"
void   sd1__detection__init
                     (SD1__DETECTION         *message)
{
  static const SD1__DETECTION init_value = SD1__DETECTION__INIT;
  *message = init_value;
}
size_t sd1__detection__get_packed_size
                     (const SD1__DETECTION *message)
{
  assert(message->base.descriptor == &sd1__detection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sd1__detection__pack
                     (const SD1__DETECTION *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sd1__detection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sd1__detection__pack_to_buffer
                     (const SD1__DETECTION *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sd1__detection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SD1__DETECTION *
       sd1__detection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SD1__DETECTION *)
     protobuf_c_message_unpack (&sd1__detection__descriptor,
                                allocator, len, data);
}
void   sd1__detection__free_unpacked
                     (SD1__DETECTION *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sd1__detection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sd1__detection__field_descriptors[5] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SD1__DETECTION, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SD1__DETECTION, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SD1__DETECTION, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SD1__DETECTION, h),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SD1__DETECTION, label),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sd1__detection__field_indices_by_name[] = {
  3,   /* field[3] = h */
  4,   /* field[4] = label */
  2,   /* field[2] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange sd1__detection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sd1__detection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SD1.DETECTION",
  "DETECTION",
  "SD1__DETECTION",
  "SD1",
  sizeof(SD1__DETECTION),
  5,
  sd1__detection__field_descriptors,
  sd1__detection__field_indices_by_name,
  1,  sd1__detection__number_ranges,
  (ProtobufCMessageInit) sd1__detection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
