/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: detect_pipe.proto */

#ifndef PROTOBUF_C_detect_5fpipe_2eproto__INCLUDED
#define PROTOBUF_C_detect_5fpipe_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SD1__DETECTION SD1__DETECTION;


/* --- enums --- */


/* --- messages --- */

/*
 *Message start
 */
struct  _SD1__DETECTION
{
  ProtobufCMessage base;
  float x;
  float y;
  float w;
  float h;
  char *label;
};
#define SD1__DETECTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sd1__detection__descriptor) \
    , 0, 0, 0, 0, (char *)protobuf_c_empty_string }


/* SD1__DETECTION methods */
void   sd1__detection__init
                     (SD1__DETECTION         *message);
size_t sd1__detection__get_packed_size
                     (const SD1__DETECTION   *message);
size_t sd1__detection__pack
                     (const SD1__DETECTION   *message,
                      uint8_t             *out);
size_t sd1__detection__pack_to_buffer
                     (const SD1__DETECTION   *message,
                      ProtobufCBuffer     *buffer);
SD1__DETECTION *
       sd1__detection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sd1__detection__free_unpacked
                     (SD1__DETECTION *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SD1__DETECTION_Closure)
                 (const SD1__DETECTION *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sd1__detection__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_detect_5fpipe_2eproto__INCLUDED */
