'''
* Author: Chance Reimer
* Purpose: Create python thread that will poll the ZMQ socket generated by the Deepstream SDK
* 	   The thread will grab information, package them in a detection class, and pass them
*	   to the main thread. 
*
'''

class deepstream_socket_thread:
	
